// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCOTA_H
#define UI_SCOTA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scota
extern void ui_scota_screen_init(void);
extern void ui_scota_screen_destroy(void);
extern lv_obj_t * ui_scota;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_ipaddr;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scota;
extern lv_obj_t * uic_title;
extern lv_obj_t * uic_ipaddr;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

