// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCHOME_H
#define UI_SCHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_schome
extern void ui_schome_screen_init(void);
extern void ui_schome_screen_destroy(void);
extern lv_obj_t * ui_schome;
extern lv_obj_t * ui_top;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_div;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_power;
extern lv_obj_t * ui_center;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_cellcontainer;
extern lv_obj_t * ui_bottom;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_div1;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_2366_direct;
extern lv_obj_t * ui_2366_power;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_2366_voltage;
extern lv_obj_t * ui_2366_current;
// CUSTOM VARIABLES
extern lv_obj_t * uic_schome;
extern lv_obj_t * uic_div;
extern lv_obj_t * uic_cellcontainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

