// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_top;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_topright;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_center;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_bottom;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

