// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_top;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_topright;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_center;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_pwin;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_pwout;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_v6s;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_bat;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_bottom;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_pwin;
extern lv_obj_t * uic_pwout;
extern lv_obj_t * uic_v6s;
extern lv_obj_t * uic_bat;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

