// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_ipaddr;
lv_obj_t * uic_title;
lv_obj_t * uic_scota;
lv_obj_t * ui_scota = NULL;
lv_obj_t * ui_title = NULL;
lv_obj_t * ui_ipaddr = NULL;
// event funtions

// build funtions

void ui_scota_screen_init(void)
{
    ui_scota = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scota, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scota, lv_color_hex(0x010447), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scota, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_scota, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_scota, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_scota, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_scota, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_scota, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_scota, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_scota);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title, 0);
    lv_obj_set_y(ui_title, 10);
    lv_obj_set_align(ui_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_title, "Firmware upgrade");
    lv_obj_set_style_text_color(ui_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipaddr = lv_label_create(ui_scota);
    lv_obj_set_width(ui_ipaddr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ipaddr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ipaddr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipaddr, "IP: 192.168.99.1");
    lv_obj_set_style_text_color(ui_ipaddr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ipaddr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ipaddr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ipaddr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ipaddr, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ipaddr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_scota = ui_scota;
    uic_title = ui_title;
    uic_ipaddr = ui_ipaddr;

}

void ui_scota_screen_destroy(void)
{
    if(ui_scota) lv_obj_del(ui_scota);

    // NULL screen variables
    uic_scota = NULL;
    ui_scota = NULL;
    uic_title = NULL;
    ui_title = NULL;
    uic_ipaddr = NULL;
    ui_ipaddr = NULL;

}
